services:
  - type: web
    name: footshop-backend
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: footshop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: footshop-db
    plan: free